# This file is separated into different logical section of an Oasis workflow.
# Each section specified will be run based on key value pairs define in it.
# Essentially, each section conveniently runs many underlying webservices.
# The sections will be run in order.

[meta]
url = "http://127.0.0.1:8000"
log_file = "spittal.log"
log_level = "DEBUG"
system_config = 1

[login]
user = "root"
password = "password"

[model]
name = "Mytestmodel"
do_timestamps = true
key = "Modelkey"

# Optionally, set a default upload directory prefix.
directory_path = "C:\\Users\\OasisUser\\Desktop\\OasisImplementationModels-master\\examples\\output"

  [model.dict.areaperil]
  filename = "dict_areaperil.csv"
  module_supplier_id = 3

  [model.dict.event]
  filename = "dict_event.csv"
  module_supplier_id = 3

  [model.dict.vuln]
  filename = "dict_vuln.csv"
  module_supplier_id = 3
  
  [model.dict.hazardintensitybin]
  filename = "dict_hazardintensitybin.csv"
  module_supplier_id = 3
  
  [model.version.hazfp]
  filename = "version_hazfp.csv"
  module_supplier_id = 3

  [model.version.vuln]
  filename = "version_vuln.csv"
  module_supplier_id = 3  
  
  [model.dict.damagebin]
  filename = "dict_damagebin.csv"
  module_supplier_id = 3

[exposure]
name = "Mytestexposure"
do_timestamps = true

# Optionally, set a default upload directory prefix.
directory_path = "C:\\Users\\OasisUser\\Desktop\\OasisImplementationModels-master\\examples\\output"

  [exposure.dict.exposure]
  filename = "dict_exposure.csv"
  module_supplier_id = 3
  
  [exposure.version.exposure]
  filename = "version_exposure.csv"
  module_supplier_id = 3
  
  [exposure.version.correlation]
  filename = "MyCorrelations_OASIS.csv"
  module_supplier_id = 3

[benchmark]
name = "mybenchmark"
chunk_size = 10
min_chunk = 3
max_chunk = 10

[gul]
name = "mygul"

[pubgul]
name = "mypubgul123"
filename = "Pub_GUL_file_Oasis123.csv"
module_supplier_id = 3
